### ISSUE TITLE
상태 관리 어떤거 쓸지 정해야할 듯

### ISSUE THREAD

**Issue by dongwooklee96** [dongwooklee96/pre_metlife_hackerton_front#3]

**Comment by yongseong2** [comment]
Redux toolkit 이나 기본 구현 Context 사용가능합니다

**Comment by jja6312** [comment]
현재 BE로 배정되긴했는데 Zustand 간단하게 사용가능합니다

**Comment by dongwooklee96** [comment]
@dongwooklee96 @yongseong2 @jja6312 
저는 사실 상태 관리 툴에 익숙한 편은 아니라 가이드 해주실 분 있으시다면 따라갈 수 있어요
다른 의견 있으시면 댓글 남겨주시고
없으시다면 Redux toolkit, Zustand 중에서 고르는 것으로 하겠습니다.

**Comment by yongseong2** [comment]
Redux 툴킷으로 결정나게되면 오늘 저녁에 시간날때 기본 세팅 해놓겠습니다

**Comment by dongwooklee96** [comment]
그럼 오늘 20시까지 별다른 의견 없으시다면 리덕스 툴킷으로 결정하도록하겠습니다~

**Comment by yongseong2** [comment]
시간이 남아서 Redux Toolkit 관련 브랜치 파서

https://github.com/dongwooklee96/pre_metlife_hackerton_front/pull/9

풀리퀘 올려놨습니다. 다른 상태관리 사용하게되면 편하게 닫으셔도 됩니다.

```
설치한 라이브러리
 "react-redux": "^9.1.0",
"redux-persist": "^6.0.0",
"@types/redux-logger": "^3.0.13",
```
간단한 사용방법은

```
// App.tsx
  const dispatch = useAppDispatch();
  const setToken = () => {
    dispatch(login({ accessToken: 'sampleToken' }));
  };
  
   const { accessToken } = useAppSelector((state) => state.user);
  ```
  
  위 코드와 같이 사용하실 수 있습니다. sample 코드로 /store/modules/user.ts 에 간단한 userSlice.ts 작성해놨습니다.
